**2.1.1 Getting Started**

In [1]:
#@ Importing the package
import torch

In [2]:
#@ Create a vector of evenly spaced values
x = torch.arange(10, dtype=torch.float32)
print(x)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [3]:
#@ Inspecting total number of elements in tensor
x.numel()

10

In [4]:
#@ Inspecting shape 
x.shape

torch.Size([10])

In [5]:
#@ Change the shape of tensor without altering its size or values
X = x.reshape(2, 5)
print(X)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])


In [6]:
#@ Creating tensor with all elements set to zeros
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
#@ Creating a tensor with all ones by invoking ones
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
#@ Randomly initialized sample
torch.randn(3, 4)

tensor([[-0.3598,  1.4231, -0.2068,  0.8653],
        [-0.5152,  0.7670,  0.9289,  0.7218],
        [-0.8719, -0.1446,  0.4160, -0.0408]])

In [9]:
#@ Constructing tensors by supplying the exact values
torch.tensor([[1, 2, 3, 4], [5, 6, 3, 2], [9, 9 , 1, 2]])

tensor([[1, 2, 3, 4],
        [5, 6, 3, 2],
        [9, 9, 1, 2]])

**2.1.2 Indexing and Slicing**

In [10]:
#@ Acessing tensor elements by indexing
X[-1], X[:]

(tensor([5., 6., 7., 8., 9.]),
 tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]))

In [11]:
#@ Writing elements of matrix by specifying indices
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6., 17.,  8.,  9.]])

In [12]:
X[0, :] = 12
X

tensor([[12., 12., 12., 12., 12.],
        [ 5.,  6., 17.,  8.,  9.]])

**2.1.3 Operations**

In [13]:
#@ Performing unary calculation
torch.exp(X)

tensor([[1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
        [1.4841e+02, 4.0343e+02, 2.4155e+07, 2.9810e+03, 8.1031e+03]])

In [14]:
#@ Mathematical Operations
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
#@ Concatenating multiple tensor together
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [16]:
#@ Constructing a binary tensor via logical statements
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
#@ Summing all the elements in the tensor yields tensor with one element
X.sum()

tensor(66.)

**2.1.4 Broadcasting**

In [18]:
#@ Broadcasting Mechanism
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

**2.1.5 Saving Memory**

In [20]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [21]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X+Y
print('id(Z):', id(Z))

id(Z): 140318848965248
id(Z): 140318848965248


In [22]:
before = id(X)
X += Y
id(X) == before

True

**2.1.6 Conversion to Other Python Objects**

In [23]:
#@ Converting to a NumPy tensor(ndarray)
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [24]:
#@ Converting a size tensor to a Python scalar
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

**Summary**

The tensor class is the main interface for storing and manipulating data in deep learning libraries. Tensors provide a variety of functionalities including construction routintes; indexing and slicing; basic mathematics operations; broadcasting; memory-efficient assignment; and conversion to and from other Python objects.