**2.3.1 Scalars**

In [1]:
#@ Scalars
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

**2.3.2 Vectors**

In [2]:
#@ Vectors
x = torch.arange(3)
x

tensor([0, 1, 2])

In [3]:
#@ indexing the tensors elements
x[2]

tensor(2)

In [4]:
#@ Checking length of the vector
len(x)

3

In [5]:
#@ Checking shape of the vectos
x.shape

torch.Size([3])

**2.3.3 Matrices**

In [6]:
#@ Matrices
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [7]:
#@ Accessing transpose matrix
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [8]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

**2.3.4 Tensors**

In [9]:
#@ Creating tensor
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

**2.3.5 Basic Properties of Tensor Arithmetic**

In [10]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)

#@ Assign a copy of 'A' to 'B' by allocating new memory
B = A.clone()
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [11]:
#@ Adding each element of the tensor to the scalar
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

**2.3.6 Reduction**

In [12]:
#@ Calculating sum of the tensor's elements
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [13]:
#@ Sum of elements of an m * n matrix
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [14]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [15]:
#@ Specifying axis=1
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [16]:
#@ Reducing a matrix along both rows and columns
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [17]:
#@ Calculating mean
A.mean(), A.sum() / A.numel()

#@ reducing a tensor along specific axes
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

**2.3.7 Non-Reducing Sum**

In [18]:
#@ Implementing non reduction sum
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [19]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [20]:
#@ Calculating cumulative sum of elements A along some axis
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

**2.3.8 Dot Products**

In [21]:
#@ Calculating dot products
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [22]:
#@ Performing elementwise multiplication followed by sum
torch.sum(x*y)

tensor(3.)

**2.3.9 Matrix - Vector products**

In [23]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

**2.3.10 Matrix-Matrix Multiplication**

In [24]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

**2.3.11 Norms**

In [25]:
#@ Calculating l2 norm
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [26]:
#@ Composing absolute value with sum operation
torch.abs(u).sum()

tensor(7.)

In [27]:
#@ Create frobenius norm of a matrix
torch.norm(torch.ones((4, 9)))

tensor(6.)